TLE5012B: C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/src/Tle5012b.cpp File Reference
Tle5012b.cpp File Reference
#include "Tle5012b.h"
Functions
Tle5012b.h - Library for Arduino for the TLE5012B angle sensor.
GMR-based angle sensor for angular position sensing in automotive applications
Author
Infineon Technologies AG (Dr.Olaf Filies)
Copyright
Infineon Technologies AG
Version
2.0.1
The TLE5012B is a 360° angle sensor that detects the orientation of a magnetic field. This is achieved by measuring sine and cosine angle components with monolithic integrated Giant Magneto Resistance (iGMR) elements. These raw signals (sine and cosine) are digitally processed internally to calculate the angle orientation of the magnetic field (magnet). The TLE5012B is a pre-calibrated sensor. The calibration parameters are stored in laser fuses. At start-up the values of the fuses are written into flip-flops, where these values can be changed by the application-specific parameters. Further precision of the angle measurement over a wide temperature range and a long lifetime can be improved by enabling an optional internal autocalibration algorithm. Data communications are accomplished with a bi-directional Synchronous Serial Communication (SSC) that is SPI-compatible. The sensor configuration is stored in registers, which are accessible by the SSC interface. Additionally four other interfaces are available with the TLE5012B: Pulse-Width-Modulation (PWM) Protocol, Short-PWM-Code (SPC) Protocol, Hall Switch Mode (HSM) and Incremental Interface (IIF). These interfaces can be used in parallel with SSC or alone. Pre-configured sensor derivates with different interface settings are available. Online diagnostic functions are provided to ensure reliable operation.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
uint8_t getFirstByte (uint16_t twoByteWord)
Gets the first byte of a 2 byte word.
uint8_t getSecondByte (uint16_t twoByteWord)
Gets the second byte of the 2 byte word.
uint8_t crc8 (uint8_t *data, uint8_t length)
Function for calculation the CRC.
uint8_t crcCalc (uint8_t *crcData, uint8_t length)
Function for calculation of the CRC.
double calculateAngleSpeed (double angRange, int16_t rawAngleSpeed, uint16_t firMD, uint16_t predictionVal)
Calculate the angle speed.
Function Documentation
calculateAngleSpeed()
double calculateAngleSpeed (double angRange, int16_t rawAngleSpeed, uint16_t firMD, uint16_t predictionVal)
Calculate the angle speed.
Parameters
angRange set angular range value
rawAngleSpeed raw speed value from read function
firMD
predictionVal
Returns
calculated angular speed
Definition at line 119 of file Tle5012b.cpp.
 {
     double finalAngleSpeed;
     double microsecToSec = 0.000001;
     double firMDVal;
     if (firMD == 1)
     {
         firMDVal = 42.7;
     }else if (firMD == 0)
     {
         firMDVal = 21.3;
     }else if (firMD == 2)
     {
         firMDVal = 85.3;
     }else if (firMD == 3)
     {
         firMDVal = 170.6;
     }else{
         firMDVal = 0;
     }
     finalAngleSpeed = ((angRange / POW_2_15) * ((double) rawAngleSpeed)) / (((double) predictionVal) * firMDVal * microsecToSec);
     return (finalAngleSpeed);
 }
References POW_2_15.
Referenced by Tle5012b::getAngleSpeed().
crc8()
uint8_t crc8 (uint8_t * data, uint8_t length)
Function for calculation the CRC.
Parameters
data byte long data for CRC check
length length of data
Returns
returns 8bit CRC
Definition at line 76 of file Tle5012b.cpp.
 {
     uint32_t crc;
     int16_t i, bit;
     crc = CRC_SEED;
     for (i = 0; i < length; i++)
     {
         crc ^= data[i];
         for (bit = 0; bit < 8; bit++)
         {
             if ((crc & 0x80) != 0)
             {
                 crc <<= 1;
                 crc ^= CRC_POLYNOMIAL;
             }else{
                 crc <<= 1;
             }
         }
     }
     return ((~crc) & CRC_SEED);
 }
References CRC_POLYNOMIAL, and CRC_SEED.
Referenced by crcCalc().
crcCalc()
uint8_t crcCalc (uint8_t * crcData, uint8_t length)
Function for calculation of the CRC.
Parameters
crcData byte long data for CRC check
length length of data
Returns
runs crc8 calculation and returns CRC
Definition at line 106 of file Tle5012b.cpp.
 {
     return (crc8(crcData, length));
 }
References crc8().
Referenced by Tle5012b::checkSafety(), and Tle5012b::regularCrcUpdate().
getFirstByte()
uint8_t getFirstByte (uint16_t twoByteWord)
Gets the first byte of a 2 byte word.
Parameters
twoByteWord insert word of two bytes long
Returns
returns the first byte
Definition at line 55 of file Tle5012b.cpp.
 {
     return ((uint8_t) (twoByteWord >> 8));
 }
Referenced by Tle5012b::checkSafety(), and Tle5012b::regularCrcUpdate().
getSecondByte()
uint8_t getSecondByte (uint16_t twoByteWord)
Gets the second byte of the 2 byte word.
Parameters
twoByteWord insert word of two bytes long
Returns
returns the second byte
Definition at line 65 of file Tle5012b.cpp.
 {
     return ((uint8_t) twoByteWord);
 }
Referenced by Tle5012b::checkSafety(), and Tle5012b::regularCrcUpdate().