TLE5012B: C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/examples/ReadAngleTest/ReadAngleTest.ino File Reference
ReadAngleTest.ino File Reference
#include <Tle5012b.h>
ReadAngleTest
This example reads all main Sensor registers (angle,revolution,speed,range and temperature) for a simple first test of the sensor and comunication.
Author
Infineon Technologies AG
Copyright
2019 Infineon Technologies AG
Version
2.0.1 \Attention We use default very low spee 9600 baud, but the sensor can much more, see the other examples
Tle5012b Tle5012MagneticAngleSensor
errorTypes checkError = NO_ERROR
void setup ()
void loop ()
Function Documentation
loop()
void loop ()
Definition at line 29 of file ReadAngleTest.ino.
             {
   double d = 0.0;
   double r = 0.0;
   double s = 0.0;
   double t = 0;
   int16_t b = 0;
   Tle5012MagneticAngleSensor.getAngleValue(d);
   Tle5012MagneticAngleSensor.getNumRevolutions(b);
   Tle5012MagneticAngleSensor.getAngleSpeed(s);
   Tle5012MagneticAngleSensor.getAngleRange(r);
   Tle5012MagneticAngleSensor.getTemperature(t);
   Serial.print("Temperature:"); Serial.print(t);
   Serial.print("°C\tangle:");   Serial.print(d);
   Serial.print("°\trange:");    Serial.print(r);
   Serial.print("\tspeed:");     Serial.print(s);
   Serial.print("\t Revolution:");Serial.println(b);
   delay(1000);
 }
References d, Tle5012b::getAngleRange(), Tle5012b::getAngleSpeed(), Tle5012b::getAngleValue(), Tle5012b::getNumRevolutions(), Tle5012b::getTemperature(), r, s, and Tle5012MagneticAngleSensor.
setup()
void setup ()
Definition at line 19 of file ReadAngleTest.ino.
              {
   delay(2000);
   Serial.begin(9600);
   checkError = Tle5012MagneticAngleSensor.begin();
   Serial.print("checkError: ");
   Serial.println(checkError,HEX);
   delay(1000);
   Serial.println("Init done");
 }
References Tle5012b::begin(), checkError, and Tle5012MagneticAngleSensor.
Variable Documentation
checkError
errorTypes checkError = NO_ERROR
Definition at line 17 of file ReadAngleTest.ino.
Referenced by setup().
Tle5012MagneticAngleSensor
Tle5012b Tle5012MagneticAngleSensor
Definition at line 16 of file ReadAngleTest.ino.
Referenced by loop(), and setup().