TLE5012B: Tle5012b_reg::mod1_t Struct Reference
Tle5012b_reg::mod1_t Struct Reference
< MOD_1 Interface Mode1 register offset 0x06
#include "Tle5012b_reg.h"
Public Member Functions
uint8_t fetch_IIFMOD (uint16_t reg)
boolean fetch_DSPUHOLD (uint16_t reg)
uint16_t fetch_Reserverd1 (uint16_t reg)
boolean fetch_CLKSEL (uint16_t reg)
boolean fetch_Reserverd2 (uint16_t reg)
uint8_t fetch_FIRMD (uint16_t reg)
Data Fields
uint8_t FIRMD
bits 15:14 Update Rate Setting
uint16_t Reserverd1
bits 13:5
boolean CLKSEL
bits 4:4 Switch to external clock at start-up only.
boolean Reserverd2
bits 3:3
boolean DSPUHOLD
bits 2:2 If DSPU is on hold, no watch dog reset is performed by DSPU
uint8_t IIFMOD
bits 1:0 Incremental Interface Mode
uint16_t reg
the register value
Detailed Description
< MOD_1 Interface Mode1 register offset 0x06
Definition at line 214 of file Tle5012b_reg.h.
Member Function Documentation
fetch_CLKSEL()
boolean Tle5012b_reg::mod1_t::fetch_CLKSEL (uint16_t reg) inline
Definition at line 227 of file Tle5012b_reg.h.
 {CLKSEL = (reg & 0x10) >> 4;return (CLKSEL);}
References CLKSEL, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), and reg_mod1().
fetch_DSPUHOLD()
boolean Tle5012b_reg::mod1_t::fetch_DSPUHOLD (uint16_t reg) inline
Definition at line 225 of file Tle5012b_reg.h.
 {DSPUHOLD = (reg & 0x4) >> 2;return (DSPUHOLD);}
References DSPUHOLD, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), and reg_mod1().
fetch_FIRMD()
uint8_t Tle5012b_reg::mod1_t::fetch_FIRMD (uint16_t reg) inline
Definition at line 229 of file Tle5012b_reg.h.
 {FIRMD = (reg & 0x6000) >> 13;return (FIRMD);}
References FIRMD, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), and reg_mod1().
fetch_IIFMOD()
uint8_t Tle5012b_reg::mod1_t::fetch_IIFMOD (uint16_t reg) inline
Definition at line 224 of file Tle5012b_reg.h.
 {IIFMOD = (reg & 0x3);return (IIFMOD);}
References IIFMOD, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), reg_mod1(), and setup().
fetch_Reserverd1()
uint16_t Tle5012b_reg::mod1_t::fetch_Reserverd1 (uint16_t reg) inline
Definition at line 226 of file Tle5012b_reg.h.
 {Reserverd1 = (reg & 0x8) >> 3;return (Reserverd1);}
References reg, and Reserverd1.
Referenced by reg_mod1().
fetch_Reserverd2()
boolean Tle5012b_reg::mod1_t::fetch_Reserverd2 (uint16_t reg) inline
Definition at line 228 of file Tle5012b_reg.h.
 {Reserverd2 = (reg & 0x3FE0) >> 5;return (Reserverd2);}
References reg, and Reserverd2.
Referenced by reg_mod1().
Field Documentation
CLKSEL
boolean Tle5012b_reg::mod1_t::CLKSEL
bits 4:4 Switch to external clock at start-up only.
Definition at line 218 of file Tle5012b_reg.h.
Referenced by fetch_CLKSEL().
DSPUHOLD
boolean Tle5012b_reg::mod1_t::DSPUHOLD
bits 2:2 If DSPU is on hold, no watch dog reset is performed by DSPU
Definition at line 220 of file Tle5012b_reg.h.
Referenced by fetch_DSPUHOLD().
FIRMD
uint8_t Tle5012b_reg::mod1_t::FIRMD
bits 15:14 Update Rate Setting
Definition at line 216 of file Tle5012b_reg.h.
Referenced by fetch_FIRMD().
IIFMOD
uint8_t Tle5012b_reg::mod1_t::IIFMOD
bits 1:0 Incremental Interface Mode
Definition at line 221 of file Tle5012b_reg.h.
Referenced by fetch_IIFMOD().
reg
uint16_t Tle5012b_reg::mod1_t::reg
the register value
Definition at line 222 of file Tle5012b_reg.h.
Referenced by fetch_CLKSEL(), fetch_DSPUHOLD(), fetch_FIRMD(), fetch_IIFMOD(), fetch_Reserverd1(), fetch_Reserverd2(), Tle5012b_reg::identifyInterfaceType(), Tle5012b_reg::readSensorType(), reg_mod1(), and setup().
Reserverd1
uint16_t Tle5012b_reg::mod1_t::Reserverd1
bits 13:5
Definition at line 217 of file Tle5012b_reg.h.
Referenced by fetch_Reserverd1().
Reserverd2
boolean Tle5012b_reg::mod1_t::Reserverd2
bits 3:3
Definition at line 219 of file Tle5012b_reg.h.
Referenced by fetch_Reserverd2().
The documentation for this struct was generated from the following file:
C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/src/Tle5012b_reg.h