TLE5012B: Tle5012b_reg::mod2_t Struct Reference
Tle5012b_reg::mod2_t Struct Reference
< MOD_2 Interface Mode2 register offset 0x08
#include "Tle5012b_reg.h"
Public Member Functions
uint8_t fetch_AUTOCAL (uint16_t reg)
boolean fetch_PREDICT (uint16_t reg)
boolean fetch_ANGDIR (uint16_t reg)
uint16_t fetch_ANGRANGE (uint16_t reg)
boolean fetch_Reserverd1 (uint16_t reg)
Data Fields
boolean Reserverd1
bits 15:15
uint16_t ANGRANGE
bits 14:4 Changes the representation of the angle output by multiplying the output with a factor ANG_RANGE/128.
boolean ANGDIR
bits 3:3 Inverts angle and angle speed values and revolution counter behavior.
boolean PREDICT
bits 2:2 Prediction of angle value based on current angle speed
uint8_t AUTOCAL
bits 1:0 Automatic calibration of offset and amplitude synchronicity for applications with full-turn.
uint16_t reg
the register value
Detailed Description
< MOD_2 Interface Mode2 register offset 0x08
Definition at line 254 of file Tle5012b_reg.h.
Member Function Documentation
fetch_ANGDIR()
boolean Tle5012b_reg::mod2_t::fetch_ANGDIR (uint16_t reg) inline
Definition at line 265 of file Tle5012b_reg.h.
 {ANGDIR = (reg & 0x8) >> 3;return (ANGDIR);}
References ANGDIR, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), and reg_mod2().
fetch_ANGRANGE()
uint16_t Tle5012b_reg::mod2_t::fetch_ANGRANGE (uint16_t reg) inline
Definition at line 266 of file Tle5012b_reg.h.
 {ANGRANGE = (reg & 0x7FF0) >> 4;return (ANGRANGE);}
References ANGRANGE, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), and reg_mod2().
fetch_AUTOCAL()
uint8_t Tle5012b_reg::mod2_t::fetch_AUTOCAL (uint16_t reg) inline
Definition at line 263 of file Tle5012b_reg.h.
 {AUTOCAL = (reg & 0x3);return (AUTOCAL);}
References AUTOCAL, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), mod2(), and reg_mod2().
fetch_PREDICT()
boolean Tle5012b_reg::mod2_t::fetch_PREDICT (uint16_t reg) inline
Definition at line 264 of file Tle5012b_reg.h.
 {PREDICT = (reg & 0x4) >> 2;return (PREDICT);}
References PREDICT, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), mod2(), and reg_mod2().
fetch_Reserverd1()
boolean Tle5012b_reg::mod2_t::fetch_Reserverd1 (uint16_t reg) inline
Definition at line 267 of file Tle5012b_reg.h.
 {Reserverd1 = (reg & 0x8000) >> 15;return (Reserverd1);}
References reg, and Reserverd1.
Referenced by reg_mod2(), and reg_mod4().
Field Documentation
ANGDIR
boolean Tle5012b_reg::mod2_t::ANGDIR
bits 3:3 Inverts angle and angle speed values and revolution counter behavior.
Definition at line 258 of file Tle5012b_reg.h.
Referenced by fetch_ANGDIR().
ANGRANGE
uint16_t Tle5012b_reg::mod2_t::ANGRANGE
bits 14:4 Changes the representation of the angle output by multiplying the output with a factor ANG_RANGE/128.
Definition at line 257 of file Tle5012b_reg.h.
Referenced by fetch_ANGRANGE().
AUTOCAL
uint8_t Tle5012b_reg::mod2_t::AUTOCAL
bits 1:0 Automatic calibration of offset and amplitude synchronicity for applications with full-turn.
Definition at line 260 of file Tle5012b_reg.h.
Referenced by fetch_AUTOCAL().
PREDICT
boolean Tle5012b_reg::mod2_t::PREDICT
bits 2:2 Prediction of angle value based on current angle speed
Definition at line 259 of file Tle5012b_reg.h.
Referenced by fetch_PREDICT().
reg
uint16_t Tle5012b_reg::mod2_t::reg
the register value
Definition at line 261 of file Tle5012b_reg.h.
Referenced by fetch_ANGDIR(), fetch_ANGRANGE(), fetch_AUTOCAL(), fetch_PREDICT(), fetch_Reserverd1(), Tle5012b_reg::identifyInterfaceType(), Tle5012b_reg::readSensorType(), reg_mod2(), and setup().
Reserverd1
boolean Tle5012b_reg::mod2_t::Reserverd1
bits 15:15
Definition at line 256 of file Tle5012b_reg.h.
Referenced by fetch_Reserverd1().
The documentation for this struct was generated from the following file:
C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/src/Tle5012b_reg.h