TLE5012B: Tle5012b_reg::mod3_t Struct Reference
Tle5012b_reg::mod3_t Struct Reference
< MOD_3 Interface Mode3 register offset 0x09
#include "Tle5012b_reg.h"
Public Member Functions
uint8_t fetch_PADDRV (uint16_t reg)
boolean fetch_SSCOD (uint16_t reg)
boolean fetch_SPIKEF (uint16_t reg)
uint16_t fetch_ANG_BASE (uint16_t reg)
Data Fields
uint16_t ANG_BASE
bits 15:4 Sets the 0째 angle position (12 bit value).
boolean SPIKEF
bits 3:3 Filters voltage spikes on input pads (IFC, SCK and CSQ).
boolean SSCOD
bits 2:2 SSC-Interface Data Pin Output Mode
uint8_t PADDRV
bits 1;0 Configuration of Pad-Driver
uint16_t reg
the register value
Detailed Description
< MOD_3 Interface Mode3 register offset 0x09
Definition at line 270 of file Tle5012b_reg.h.
Member Function Documentation
fetch_ANG_BASE()
uint16_t Tle5012b_reg::mod3_t::fetch_ANG_BASE (uint16_t reg) inline
Definition at line 281 of file Tle5012b_reg.h.
 {ANG_BASE = (reg & 0xFFF0) >> 4;return (ANG_BASE);}
References ANG_BASE, and reg.
Referenced by reg_mod3().
fetch_PADDRV()
uint8_t Tle5012b_reg::mod3_t::fetch_PADDRV (uint16_t reg) inline
Definition at line 278 of file Tle5012b_reg.h.
 {PADDRV = (reg & 0x3);return (PADDRV);}
References PADDRV, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), mod3(), and reg_mod3().
fetch_SPIKEF()
boolean Tle5012b_reg::mod3_t::fetch_SPIKEF (uint16_t reg) inline
Definition at line 280 of file Tle5012b_reg.h.
 {SPIKEF = (reg & 0x8) >> 3;return (SPIKEF);}
References reg, and SPIKEF.
Referenced by Tle5012b_reg::identifyInterfaceType(), mod3(), and reg_mod3().
fetch_SSCOD()
boolean Tle5012b_reg::mod3_t::fetch_SSCOD (uint16_t reg) inline
Definition at line 279 of file Tle5012b_reg.h.
 {SSCOD = (reg & 0x4) >> 2;return (SSCOD);}
References reg, and SSCOD.
Referenced by Tle5012b_reg::identifyInterfaceType(), mod3(), and reg_mod3().
Field Documentation
ANG_BASE
uint16_t Tle5012b_reg::mod3_t::ANG_BASE
bits 15:4 Sets the 0째 angle position (12 bit value).
Angle base is factory-calibrated to make the 0째 direction parallel to the edge of the chip.
Definition at line 272 of file Tle5012b_reg.h.
Referenced by fetch_ANG_BASE().
PADDRV
uint8_t Tle5012b_reg::mod3_t::PADDRV
bits 1;0 Configuration of Pad-Driver
Definition at line 275 of file Tle5012b_reg.h.
Referenced by fetch_PADDRV().
reg
uint16_t Tle5012b_reg::mod3_t::reg
the register value
Definition at line 276 of file Tle5012b_reg.h.
Referenced by fetch_ANG_BASE(), fetch_PADDRV(), fetch_SPIKEF(), fetch_SSCOD(), Tle5012b_reg::identifyInterfaceType(), Tle5012b_reg::readSensorType(), reg_mod3(), and setup().
SPIKEF
boolean Tle5012b_reg::mod3_t::SPIKEF
bits 3:3 Filters voltage spikes on input pads (IFC, SCK and CSQ).
Definition at line 273 of file Tle5012b_reg.h.
Referenced by fetch_SPIKEF().
SSCOD
boolean Tle5012b_reg::mod3_t::SSCOD
bits 2:2 SSC-Interface Data Pin Output Mode
Definition at line 274 of file Tle5012b_reg.h.
Referenced by fetch_SSCOD().
The documentation for this struct was generated from the following file:
C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/src/Tle5012b_reg.h