TLE5012B: Tle5012b_SPI Class Reference
Tle5012b_SPI Class Reference
#include "Tle5012b_SPI.h"
Public Member Functions
Tle5012b_SPI.h - Library for Arduino for the TLE5012B angle sensor.
GMR-based angle sensor for angular position sensing in automotive applications This library includes the 3-wire SPI connection for the TLE5012B -E1000/E5000/E9000 sensor2GO kits
Author
Infineon Technologies AG (Dr.Olaf Filies)
Copyright
Infineon Technologies AG
Version
2.0.1 Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Tle5012b_SPI (uint8_t spiNum=0)
Consrtuctor with optional SPI channel number which can be used for XMC4700 or any other microcontroller with more than the default SPI to connect more than four sensors at a time.
~Tle5012b_SPI ()
void begin (uint8_t miso, uint8_t mosi, uint8_t sck, uint8_t cs)
New for fetching SPI parameter.
void setCSPin (uint8_t cs)
Set the chipselect pin.
void sendReceiveSpi (uint16_t *sent_data, uint16_t size_of_sent_data, uint16_t *received_data, uint16_t size_of_received_data)
Main SPI three wire communication functions for sending and receiving data.
void sendConfig ()
set SPI to send mode
void receiveConfig ()
set SPI to receive mode
Data Fields
uint8_t mCS
Pin for chip select (pin 0.9 on test board)
uint8_t mSpiNum
Number of used SPI channel.
Private Attributes
uint8_t mMOSI
Pin for SPI MOSI (e.g.
uint8_t mMISO
Pin for SPI MISO (e.g.
uint8_t mSCK
Pin for CLOCK (e.g.
SPISettings mSPISetting
We need the original SPI class setting in case none XMC microcontroller.
Detailed Description
Definition at line 48 of file Tle5012b_SPI.h.
Constructor & Destructor Documentation
Tle5012b_SPI()
Tle5012b_SPI::Tle5012b_SPI (uint8_t spiNum = 0)
Consrtuctor with optional SPI channel number which can be used for XMC4700 or any other microcontroller with more than the default SPI to connect more than four sensors at a time.
Parameters
spiNum [in] optional SPI channel number
Definition at line 34 of file Tle5012b_SPI.cpp.
 {
     mCS = PIN_SPI_SS;
     mMISO = PIN_SPI_MISO;
     mMOSI = PIN_SPI_MOSI;
     mSCK = PIN_SPI_SCK;
     mSpiNum = spiNum;
     mSPISetting = SPISettings(SPEED,MSBFIRST,SPI_MODE1);
 }
References mCS, mMISO, mMOSI, mSCK, mSpiNum, mSPISetting, and SPEED.
~Tle5012b_SPI()
Tle5012b_SPI::~Tle5012b_SPI ()
Definition at line 43 of file Tle5012b_SPI.cpp.
 {
 }
Member Function Documentation
begin()
void Tle5012b_SPI::begin (uint8_t miso, uint8_t mosi, uint8_t sck, uint8_t cs)
New for fetching SPI parameter.
Parameters
miso [in] pin number for miso, on sensor2go boards the same than mosi
mosi [in] pin number for mosi, on sensor2go boards the same than miso
sck [in] the system clock pin for external clock driver
cs [in] chipselect pin, up to four different cs pins can be used together with the slave number
Definition at line 47 of file Tle5012b_SPI.cpp.
 {
     setCSPin(cs);
     mMOSI = mosi;
     mMISO = miso;
     mSCK = sck;
     #if defined(UC_FAMILY) && (UC_FAMILY == XMC1 || UC_FAMILY == XMC4)
         m3Wire.mosi = mapping_port_pin[mosi];
         m3Wire.miso = mapping_port_pin[miso];
         m3Wire.sck  = mapping_port_pin[sck];
         setupSPI();
         enableSpi();
     #else
         mSPISetting = SPISettings(SPEED,MSBFIRST,SPI_MODE1);
         SPIClass::begin();
         //SPI.setClockDivider(SPI_CLOCK_DIV4);
     #endif
 }
References mMISO, mMOSI, mSCK, mSPISetting, setCSPin(), and SPEED.
Referenced by Tle5012b::begin().
receiveConfig()
void Tle5012b_SPI::receiveConfig ()
set SPI to receive mode
Definition at line 220 of file Tle5012b_SPI.cpp.
     {
         pinMode(mMISO,INPUT);
         pinMode(mMOSI,INPUT);
     }
References mMISO, and mMOSI.
Referenced by sendReceiveSpi().
sendConfig()
void Tle5012b_SPI::sendConfig ()
set SPI to send mode
Any other arduino compliant library souch run through the default SPI setup.
This implement the 3-Wire SPI, so MISO/MOSI are conected short. If you want to us the buld chip with a 4-Wire SPI than checkout the special 4-Wire library
Definition at line 214 of file Tle5012b_SPI.cpp.
     {
         pinMode(mMISO,INPUT);
         pinMode(mMOSI,OUTPUT);
     }
References mMISO, and mMOSI.
Referenced by sendReceiveSpi().
sendReceiveSpi()
void Tle5012b_SPI::sendReceiveSpi (uint16_t * sent_data, uint16_t size_of_sent_data, uint16_t * received_data, uint16_t size_of_received_data)
Main SPI three wire communication functions for sending and receiving data.
Parameters
sent_data pointer two 2*unit16_t value for one command word and one data word if something should be written
size_of_sent_data the size of the command word default 1 = only command 2 = command and data word
received_data pointer to data structure buffer for the read data
size_of_received_data size of data words to be read
Definition at line 226 of file Tle5012b_SPI.cpp.
     {
         uint32_t data_index = 0;
         //send via TX
         sendConfig();
         digitalWrite(mCS, LOW);
         beginTransaction(mSPISetting);
         for(data_index = 0; data_index < size_of_sent_data; data_index++)
         {
             received_data[0] = transfer16(sent_data[data_index] );
         }
         // receive via RX
         receiveConfig();
         delayMicroseconds(5);
         for(data_index = 0; data_index < size_of_received_data; data_index++)
         {
             received_data[data_index] = transfer16(0x0000);
         }
         endTransaction();
         digitalWrite(mCS, HIGH);
     }
References mCS, mSPISetting, receiveConfig(), and sendConfig().
Referenced by Tle5012b::readBlockCRC(), Tle5012b::readFromSensor(), Tle5012b::readMoreRegisters(), Tle5012b::resetSafety(), Tle5012b::writeTempCoeffUpdate(), and Tle5012b::writeToSensor().
setCSPin()
void Tle5012b_SPI::setCSPin (uint8_t cs)
Set the chipselect pin.
This function is needed if more than one sensor is in the SPI bus
Parameters
cs [in] Pin number of the sensors chip select
Definition at line 66 of file Tle5012b_SPI.cpp.
 {
     mCS = cs;
 }
References mCS.
Referenced by begin(), Tle5012b::readBlockCRC(), Tle5012b::readFromSensor(), Tle5012b::readMoreRegisters(), Tle5012b::triggerUpdate(), Tle5012b::writeTempCoeffUpdate(), and Tle5012b::writeToSensor().
Field Documentation
mCS
uint8_t Tle5012b_SPI::mCS
Pin for chip select (pin 0.9 on test board)
Definition at line 61 of file Tle5012b_SPI.h.
Referenced by sendReceiveSpi(), setCSPin(), and Tle5012b_SPI().
mMISO
uint8_t Tle5012b_SPI::mMISO private
Pin for SPI MISO (e.g.
pin 0.7 on test board)
Definition at line 94 of file Tle5012b_SPI.h.
Referenced by begin(), receiveConfig(), sendConfig(), and Tle5012b_SPI().
mMOSI
uint8_t Tle5012b_SPI::mMOSI private
Pin for SPI MOSI (e.g.
pin 0.6 on test board);
Definition at line 93 of file Tle5012b_SPI.h.
Referenced by begin(), receiveConfig(), sendConfig(), and Tle5012b_SPI().
mSCK
uint8_t Tle5012b_SPI::mSCK private
Pin for CLOCK (e.g.
pin 0.8 on test board)
Definition at line 95 of file Tle5012b_SPI.h.
Referenced by begin(), and Tle5012b_SPI().
mSpiNum
uint8_t Tle5012b_SPI::mSpiNum
Number of used SPI channel.
Definition at line 62 of file Tle5012b_SPI.h.
Referenced by Tle5012b_SPI().
mSPISetting
SPISettings Tle5012b_SPI::mSPISetting private
We need the original SPI class setting in case none XMC microcontroller.
Definition at line 96 of file Tle5012b_SPI.h.
Referenced by begin(), sendReceiveSpi(), and Tle5012b_SPI().
The documentation for this class was generated from the following files:
C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/src/util/Tle5012b_SPI.h
C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/src/util/Tle5012b_SPI.cpp