TLE5012B: Tle5012b Class Reference
Tle5012b Class Reference
#include "Tle5012b.h"
Data Structures
struct safetyWord
Public Types
enum slaveNum { TLE5012B_S0 = 0x0000, TLE5012B_S1 = 0x2000, TLE5012B_S2 = 0x4000, TLE5012B_S3 = 0x6000 }
Offset for the slave number register to identify the right selected slave.
typedef struct Tle5012b::safetyWord safetyWord_t
Public Member Functions
errorTypes readActiveStatus (uint16_t &data)
The next functions are used primarily for storing the parameters and control of how the sensor works.
Data Fields
Tle5012b_SPI * _spiConnection
SPI library for 3/4wire setup.
uint8_t mEN
Pin to switch on/off the sensor.
uint8_t mMOSI
Pin for SPI MOSI (pin 0.6 on test board);.
uint8_t mMISO
Pin for SPI MISO (pin 0.7 on test board)
uint8_t mSCK
Pin for CLOCK (pin 0.8 on test board)
uint8_t mCS
Pin for chip select (pin 0.9 on test board)
slaveNum mSlave
actual set slave number
safetyWord safetyStatus
uint16_t safetyWord
the last fetched safety word
Private Attributes
uint16_t _command [2]
command write data [0] = command [1] = data to write
uint16_t _received [0x0030]
fetched data from sensor with last word = safety word
uint16_t _registers [0x0008]
keeps track of the values stored in the 8 _registers, for which the CRC is calculated
Tle5012b.h - Library for Arduino for the TLE5012B angle sensor.
GMR-based angle sensor for angular position sensing in automotive applications
Author
Infineon Technologies AG (Dr.Olaf Filies)
Copyright
Infineon Technologies AG
Version
2.0.1
The TLE5012B is a 360° angle sensor that detects the orientation of a magnetic field. This is achieved by measuring sine and cosine angle components with monolithic integrated Giant Magneto Resistance (iGMR) elements. These raw signals (sine and cosine) are digitally processed internally to calculate the angle orientation of the magnetic field (magnet). The TLE5012B is a pre-calibrated sensor. The calibration parameters are stored in laser fuses. At start-up the values of the fuses are written into flip-flops, where these values can be changed by the application-specific parameters. Further precision of the angle measurement over a wide temperature range and a long lifetime can be improved by enabling an optional internal autocalibration algorithm. Data communications are accomplished with a bi-directional Synchronous Serial Communication (SSC) that is SPI-compatible. The sensor configuration is stored in registers, which are accessible by the SSC interface. Additionally four other interfaces are available with the TLE5012B: Pulse-Width-Modulation (PWM) Protocol, Short-PWM-Code (SPC) Protocol, Hall Switch Mode (HSM) and Incremental Interface (IIF). These interfaces can be used in parallel with SSC or alone. Pre-configured sensor derivates with different interface settings are available. Online diagnostic functions are provided to ensure reliable operation.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holders nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Tle5012b ()
constructor for the Sensor
~Tle5012b ()
destructor stops the Sensor
errorTypes begin ()
All these functions cover the SPI interface and should be implemented into XMC SPI wrapper.
errorTypes begin (uint8_t cs, slaveNum slave=TLE5012B_S0)
errorTypes begin (Tle5012b_SPI &bus, uint8_t cs, slaveNum slave=TLE5012B_S0)
errorTypes begin (Tle5012b_SPI &bus, uint8_t miso, uint8_t mosi, uint8_t sck, uint8_t cs, slaveNum slave=TLE5012B_S0)
void end ()
Switches the sensor off and ends the comunication.
void triggerUpdate ()
Triggers an update in the register buffer.
void enableSensor ()
Function enables Sensor by switch on EN pin which is only possible on Sensor2go shields, but also sets chipselect high.
void disableSensor ()
Functions disables Sensor by switch off EN pin (only possible on Sensor2go shield)
errorTypes readBlockCRC ()
Reads the block of _registers from addresses 08 - 0F in order to figure out the CRC.
errorTypes readFromSensor (uint16_t command, uint16_t &data, updTypes upd=UPD_low, safetyTypes safe=SAFE_high)
General read function for reading _registers from the Tle5012b.
errorTypes readMoreRegisters (uint16_t command, uint16_t data[], updTypes upd=UPD_low, safetyTypes safe=SAFE_high)
Can be used to read 1 or more consecutive _registers, and the values used to read 1 or more than 1 consecutive _registers.
errorTypes readStatus (uint16_t &data, updTypes upd=UPD_low, safetyTypes safe=SAFE_high)
This functions reads the main status word for the sensor, mainly for checking with the additional safety word.
errorTypes readActivationStatus (uint16_t &data, updTypes upd=UPD_low, safetyTypes safe=SAFE_high)
This functions reads activation status word for the sensor, which held on/off information for all optional checks and additional functions.
errorTypes readIntMode1 (uint16_t &data)
read register offset 0x06
errorTypes readSIL (uint16_t &data)
read register offset 0x07
errorTypes readIntMode2 (uint16_t &data)
read register offset 0x08
errorTypes readIntMode3 (uint16_t &data)
read register offset 0x09
errorTypes readOffsetX (uint16_t &data)
read register offset 0x0A
errorTypes readOffsetY (uint16_t &data)
read register offset 0x0B
errorTypes readSynch (uint16_t &data)
read register offset 0x0C
errorTypes readIFAB (uint16_t &data)
read register offset 0x0D
errorTypes readIntMode4 (uint16_t &data)
read register offset 0x0E
errorTypes readTempCoeff (uint16_t &data)
read register offset 0x0F
errorTypes readTempDMag (uint16_t &data)
read register offset 0x14
errorTypes readTempRaw (uint16_t &data)
read register offset 0x15
errorTypes readTempIIFCnt (uint16_t &data)
read register offset 0x20
errorTypes readTempT25 (uint16_t &data)
read register offset 0x30
errorTypes readRawX (int16_t &data)
The rawX value is signed 16 bit value.
errorTypes readRawY (int16_t &data)
The rawY value is signed 16 bit value.
errorTypes getAngleRange (double &angleRange)
returns the Angle Range Angle Range is stored in bytes 14 - 4 of MOD_2.
errorTypes getAngleValue (double &angleValue)
Returns the angleValue calculated on the base of a 15 bit signed integer.
errorTypes getAngleValue (double &angleValue, int16_t &rawAnglevalue, updTypes upd=UPD_low, safetyTypes safe=SAFE_high)
Same function as before but also returns a pointer to the raw data.
errorTypes getNumRevolutions (int16_t &numRev, updTypes upd=UPD_low, safetyTypes safe=SAFE_high)
Returns the number of revolutions done from the angle value which is a 9 bit signed integer.
errorTypes getTemperature (double &temp)
Return the temperature.
errorTypes getTemperature (double &temp, int16_t &rawTemp, updTypes upd=UPD_low, safetyTypes safe=SAFE_high)
Same as above but also returns a pointer to the raw data.
errorTypes getAngleSpeed (double &angleSpeed)
Returns the calculated angle speed.
errorTypes getAngleSpeed (double &angleSpeed, int16_t &rawSpeed, updTypes upd=UPD_low, safetyTypes safe=SAFE_high)
Same as above but also returns a pointer to the raw data.
errorTypes writeSlaveNumber (uint16_t dataToWrite)
Function sets the SNR register with the correct slave number.
errorTypes writeToSensor (uint16_t command, uint16_t dataToWrite, bool changeCRC)
General write function for writing registers to the Tle5012b.
errorTypes writeTempCoeffUpdate (uint16_t dataToWrite)
This function is used in order to update the CRC in the register 0F(second byte)
errorTypes writeActivationStatus (uint16_t dataToWrite)
Standard function used for updating the CRC.
errorTypes writeIntMode1 (uint16_t dataToWrite)
write register offset 0x06
errorTypes writeSIL (uint16_t dataToWrite)
write register offset 0x07
errorTypes writeIntMode2 (uint16_t dataToWrite)
write register offset 0x08
errorTypes writeIntMode3 (uint16_t dataToWrite)
write register offset 0x09
errorTypes writeOffsetX (uint16_t dataToWrite)
write register offset 0x0A
errorTypes writeOffsetY (uint16_t dataToWrite)
write register offset 0x0B
errorTypes writeSynch (uint16_t dataToWrite)
write register offset 0x0C
errorTypes writeIFAB (uint16_t dataToWrite)
write register offset 0x0D
errorTypes writeIntMode4 (uint16_t dataToWrite)
write register offset 0x0E
errorTypes writeTempCoeff (uint16_t dataToWrite)
write register offset 0x0F
errorTypes regularCrcUpdate ()
This function is called each time any register in the range 08 - 0F(first byte) is changed.
errorTypes checkSafety (uint16_t safety, uint16_t command, uint16_t *readreg, uint16_t length)
checks the safety by looking at the safety word and calculating the CRC such that the data received is valid
void resetSafety ()
When an error occurs in the safety word, the error bit remains 0(error), until the status register is read again.
Detailed Description
Definition at line 141 of file Tle5012b.h.
Member Typedef Documentation
safetyWord_t
typedef struct Tle5012b::safetyWord Tle5012b::safetyWord_t
Member Enumeration Documentation
slaveNum
enum Tle5012b::slaveNum
Offset for the slave number register to identify the right selected slave.
Max 4 slaves with separated CSQ lines are possible. If more than one sensor is used on the SPI interface, than the SNR register must we written with the correct slave number
Enumerator
TLE5012B_S0
TLE5012B_S0 default setting for only one sensor on the SPI.
TLE5012B_S1
TLE5012B_S1 second sensor needs also a second CSQ.
TLE5012B_S2
TLE5012B_S2 third sensor and dito.
TLE5012B_S3
TLE5012B_S3 fourth sensor and dito.
Definition at line 153 of file Tle5012b.h.
     {
         TLE5012B_S0 = 0x0000,
         TLE5012B_S1 = 0x2000,
         TLE5012B_S2 = 0x4000,
         TLE5012B_S3 = 0x6000
     };
Constructor & Destructor Documentation
Tle5012b()
Tle5012b::Tle5012b ()
constructor for the Sensor
Definition at line 145 of file Tle5012b.cpp.
 {
     _spiConnection = &SPI;
     safetyWord = 0;
     mSlave = TLE5012B_S0;
     mEN = PIN_SPI_EN;
     mCS = SS;
     mMISO = MISO;
     mMOSI = MOSI;
     mSCK = SCK;
 }
References _spiConnection, mCS, mEN, mMISO, mMOSI, mSCK, mSlave, PIN_SPI_EN, and TLE5012B_S0.
~Tle5012b()
Tle5012b::~Tle5012b ()
destructor stops the Sensor
Definition at line 157 of file Tle5012b.cpp.
 {
     end();
 }
References end().
Member Function Documentation
begin() [1/4]
errorTypes Tle5012b::begin ()
All these functions cover the SPI interface and should be implemented into XMC SPI wrapper.
In 3wire SPI mode miso and mosi are connected together, so read and write operations are on the same line. In 4wire more read and write are separated. The system clock SCK and the sensor enable EN line are used for all slaves whereas the chip select line CS must we set unique for each slave. A max of four slaves on one SPI interface are possible
Returns
CRC error type
Parameters
[in] bus a SPIClass object
[in] miso MISO pin for the SPI/SSC interface
[in] mosi MOSI pin for the SPI/SSC interface
[in] sck system clock pin for external sensor clock setting
[in] cs chip select pin, must be unique for each slave
[in] slave slave offset setting for the SNR register, default is TLE5012B_S0
Definition at line 162 of file Tle5012b.cpp.
 {
     return (begin(*_spiConnection, mMISO, mMOSI, mSCK, mCS, mSlave));
 }
References _spiConnection, mCS, mMISO, mMOSI, mSCK, and mSlave.
Referenced by begin(), and setup().
begin() [2/4]
errorTypes Tle5012b::begin (uint8_t cs, slaveNum slave = TLE5012B_S0)
Definition at line 166 of file Tle5012b.cpp.
 {
     return (begin(*_spiConnection, mMISO, mMOSI, mSCK, cs, slave ));
 }
References _spiConnection, begin(), mMISO, mMOSI, and mSCK.
begin() [3/4]
errorTypes Tle5012b::begin (Tle5012b_SPI & bus, uint8_t cs, slaveNum slave = TLE5012B_S0)
Definition at line 170 of file Tle5012b.cpp.
 {
     return (begin(bus, mMISO, mMOSI, mSCK, cs, slave ));
 }
References begin(), mMISO, mMOSI, and mSCK.
begin() [4/4]
errorTypes Tle5012b::begin (Tle5012b_SPI & bus, uint8_t miso, uint8_t mosi, uint8_t sck, uint8_t cs, slaveNum slave = TLE5012B_S0)
Definition at line 174 of file Tle5012b.cpp.
 {
     mCS = cs;
     mMISO = miso;
     mMOSI = mosi;
     mSCK = sck;
     mSlave = slave;
     _spiConnection = &bus;
     _spiConnection->begin( miso, mosi, sck, cs);
     enableSensor();
     writeSlaveNumber(mSlave);
     return (readBlockCRC());
 }
References _spiConnection, Tle5012b_SPI::begin(), enableSensor(), mCS, mMISO, mMOSI, mSCK, mSlave, readBlockCRC(), and writeSlaveNumber().
checkSafety()
errorTypes Tle5012b::checkSafety (uint16_t safety, uint16_t command, uint16_t * readreg, uint16_t length) private
checks the safety by looking at the safety word and calculating the CRC such that the data received is valid
Parameters
safety register with the CRC check data
command the command to execute the write
readreg pointer to the read data
length the length of the data structure
Returns
CRC error type
Definition at line 302 of file Tle5012b.cpp.
 {
     errorTypes errorCheck;
     safetyWord = safety;
     if (!((safety) & SYSTEM_ERROR_MASK))
     {
         errorCheck = SYSTEM_ERROR;
         //resetSafety();
     } else if (!((safety) & INTERFACE_ERROR_MASK))
     {
         errorCheck = INTERFACE_ERROR_MASK;
         //resetSafety();
     } else if (!((safety) & INV_ANGLE_ERROR_MASK))
     {
         errorCheck = INV_ANGLE_ERROR_MASK;
         //resetSafety();
     }else{
         //resetSafety();
         uint16_t lengthOfTemp = length * 2 + 2;
         uint8_t temp[lengthOfTemp];
         temp[0] = getFirstByte(command);
         temp[1] = getSecondByte(command);
         for (uint16_t i = 0; i < length; i++)
         {
             temp[2 + 2 * i] = getFirstByte(readreg[i]);
             temp[2 + 2 * i + 1] = getSecondByte(readreg[i]);
         }
         uint8_t crcReceivedFinal = getSecondByte(safety);
         uint8_t crc = crcCalc(temp, lengthOfTemp);
         if (crc == crcReceivedFinal)
         {
             errorCheck = NO_ERROR;
         }else{
             errorCheck = CRC_ERROR;
             resetSafety();
         }
     }
     return (errorCheck);
 }
References command, CRC_ERROR, crcCalc(), getFirstByte(), getSecondByte(), INTERFACE_ERROR_MASK, INV_ANGLE_ERROR_MASK, NO_ERROR, resetSafety(), SYSTEM_ERROR, and SYSTEM_ERROR_MASK.
Referenced by readBlockCRC(), readFromSensor(), readMoreRegisters(), writeTempCoeffUpdate(), and writeToSensor().
disableSensor()
void Tle5012b::disableSensor ()
Functions disables Sensor by switch off EN pin (only possible on Sensor2go shield)
Definition at line 212 of file Tle5012b.cpp.
 {
     digitalWrite(mEN, LOW);
 }
References mEN.
Referenced by end().
enableSensor()
void Tle5012b::enableSensor ()
Function enables Sensor by switch on EN pin which is only possible on Sensor2go shields, but also sets chipselect high.
So it is called always.
Definition at line 204 of file Tle5012b.cpp.
 {
     pinMode(mEN, OUTPUT);
     digitalWrite(mEN, HIGH);
     pinMode(mCS, OUTPUT);
     digitalWrite(mCS, HIGH);
 }
References mCS, and mEN.
Referenced by begin().
end()
void Tle5012b::end ()
Switches the sensor off and ends the comunication.
Definition at line 188 of file Tle5012b.cpp.
 {
     disableSensor();
 }
References disableSensor().
Referenced by ~Tle5012b().
getAngleRange()
errorTypes Tle5012b::getAngleRange (double & angleRange)
returns the Angle Range Angle Range is stored in bytes 14 - 4 of MOD_2.
Parameters
angleRange pointer to 16bit double value
Returns
CRC error type
Definition at line 595 of file Tle5012b.cpp.
 {
     uint16_t rawData = 0;
     errorTypes status = readIntMode2(rawData);
     if (status != NO_ERROR)
     {
         return (status);
     }
     //Angle Range is stored in bytes 14 - 4, so you have to do this bit shifting to get the right value
     rawData &= GET_BIT_14_4;
     rawData >>= 4;
     angleRange = ANGLE_360_VAL * (POW_2_7 / (double) (rawData));
     return (status);
 }
References ANGLE_360_VAL, GET_BIT_14_4, NO_ERROR, POW_2_7, and readIntMode2().
Referenced by loop().
getAngleSpeed() [1/2]
errorTypes Tle5012b::getAngleSpeed (double & angleSpeed)
Returns the calculated angle speed.
The angle speed is a 15 bit signed integer, however, the register returns 16 bits, so we need to do some bit arithmetic.
Parameters
[in,out] angleSpeed pointer to 16bit double value
Returns
CRC error type
Definition at line 545 of file Tle5012b.cpp.
 {
     int16_t rawSpeed = 0;
     return (getAngleSpeed(finalAngleSpeed, rawSpeed, UPD_low, SAFE_high));
 }
References SAFE_high, and UPD_low.
Referenced by loop().
getAngleSpeed() [2/2]
errorTypes Tle5012b::getAngleSpeed (double & angleSpeed, int16_t & rawSpeed, updTypes upd = UPD_low, safetyTypes safe = SAFE_high)
Same as above but also returns a pointer to the raw data.
Parameters
[in,out] angleSpeed angleSpeed pointer to 16bit double value
[in,out] rawSpeed pointer to int16_t raw value data
[in] upd read from update (UPD_high) register or directly (default, UPD_low)
[in] safe generate safety word (default, SAFE_high) or no (SAFE_low)
Returns
CRC error type
Definition at line 550 of file Tle5012b.cpp.
 {
     int8_t numOfData = 0x5;
     uint16_t rawData[numOfData];
     errorTypes status = readMoreRegisters(REG_ASPD + numOfData, rawData, upd, safe);
     if (status != NO_ERROR)
     {
         return (status);
     }
     // Prepare raw speed
     rawSpeed = rawData[0];
     rawSpeed = (rawSpeed & (DELETE_BIT_15));
     //check if the value received is positive or negative
     if (rawSpeed & CHECK_BIT_14)
     {
         rawSpeed = rawSpeed - CHANGE_UINT_TO_INT_15;
     }
     // Prepare firMDVal
     uint16_t firMDVal = rawData[3];
     firMDVal >>= 14;
     // Prepare intMode2Prediction
     uint16_t intMode2Prediction = rawData[5];
     if (intMode2Prediction & 0x0004)
     {
         intMode2Prediction = 3;
     }else{
         intMode2Prediction = 2;
     }
     // Prepare angle range
     uint16_t rawAngleRange = rawData[5];
     rawAngleRange &= GET_BIT_14_4;
     rawAngleRange >>= 4;
     double angleRange = ANGLE_360_VAL * (POW_2_7 / (double) (rawAngleRange));
     //checks the value of fir_MD according to which the value in the calculation of the speed will be determined
     //according to if prediction is enabled then, the formula for speed changes
     finalAngleSpeed = calculateAngleSpeed(angleRange, rawSpeed, firMDVal, intMode2Prediction);
     return (status);
 }
References ANGLE_360_VAL, calculateAngleSpeed(), CHANGE_UINT_TO_INT_15, CHECK_BIT_14, DELETE_BIT_15, GET_BIT_14_4, NO_ERROR, POW_2_7, readMoreRegisters(), REG_ASPD, and upd.
getAngleValue() [1/2]
errorTypes Tle5012b::getAngleValue (double & angleValue)
Returns the angleValue calculated on the base of a 15 bit signed integer.
However, the register returns 16 bits, so we need to do some bit arithmetic.
Parameters
[in,out] angleValue pointer to 16bit double angle value
Returns
CRC error type
Definition at line 479 of file Tle5012b.cpp.
 {
     int16_t rawAnglevalue = 0;
     return (getAngleValue(angleValue, rawAnglevalue, UPD_low, SAFE_high));
 }
References SAFE_high, and UPD_low.
Referenced by loop(), and setup().
getAngleValue() [2/2]
errorTypes Tle5012b::getAngleValue (double & angleValue, int16_t & rawAnglevalue, updTypes upd = UPD_low, safetyTypes safe = SAFE_high)
Same function as before but also returns a pointer to the raw data.
Parameters
[in,out] angleValue pointer to 16bit double angle value
[in,out] rawAnglevalue point to an int16_t raw data value
[in] upd read from update (UPD_high) register or directly (default, UPD_low)
[in] safe generate safety word (default, SAFE_high) or no (SAFE_low)
Returns
CRC error type
Definition at line 484 of file Tle5012b.cpp.
 {
     uint16_t rawData = 0;
     errorTypes status = readFromSensor(REG_AVAL, rawData, upd, safe);
     if (status != NO_ERROR)
     {
         return (status);
     }
     rawData = (rawData & (DELETE_BIT_15));
     //check if the value received is positive or negative
     if (rawData & CHECK_BIT_14)
     {
         rawData = rawData - CHANGE_UINT_TO_INT_15;
     }
     rawAnglevalue = rawData;
     angleValue = (ANGLE_360_VAL / POW_2_15) * ((double) rawAnglevalue);
     return (status);
 }
References ANGLE_360_VAL, CHANGE_UINT_TO_INT_15, CHECK_BIT_14, DELETE_BIT_15, NO_ERROR, POW_2_15, readFromSensor(), REG_AVAL, and upd.
getNumRevolutions()
errorTypes Tle5012b::getNumRevolutions (int16_t & numRev, updTypes upd = UPD_low, safetyTypes safe = SAFE_high)
Returns the number of revolutions done from the angle value which is a 9 bit signed integer.
However, the register returns 16 bits, so we need to do some bit arithmetic. Therefore the resulting revolution can b only between -256 < numRev < 256 and it will switch from positive to negative and vice versa values at the borders.
Parameters
[in,out] numRev pointer to 16bit word for the number of revolutions
[in] upd read from update (UPD_high) register or directly (default, UPD_low)
[in] safe generate safety word (default, SAFE_high) or no (SAFE_low)
Returns
CRC error type
Definition at line 527 of file Tle5012b.cpp.
 {
     uint16_t rawData = 0;
     errorTypes status = readFromSensor(REG_AREV, rawData, upd, safe);
     if (status != NO_ERROR)
     {
         return (status);
     }
     rawData = (rawData & (DELETE_7BITS));
     //  //check if the value received is positive or negative
     if (rawData & CHECK_BIT_9)
     {
         rawData = rawData - CHANGE_UNIT_TO_INT_9;
     }
     numRev = rawData;
     return (status);
 }
References CHANGE_UNIT_TO_INT_9, CHECK_BIT_9, DELETE_7BITS, NO_ERROR, readFromSensor(), REG_AREV, and upd.
Referenced by loop().
getTemperature() [1/2]
errorTypes Tle5012b::getTemperature (double & temp)
Return the temperature.
The temperature value is a 9 bit signed integer. However, the register returns 16 bits, so we need to do some bit arithmetic.
Parameters
[in,out] temp pointer to 16bit double value of the temperature
Returns
CRC error type
Definition at line 503 of file Tle5012b.cpp.
 {
     int16_t rawTemp = 0;
     return (getTemperature(temperature, rawTemp, UPD_low, SAFE_high));
 }
References SAFE_high, and UPD_low.
Referenced by loop().
getTemperature() [2/2]
errorTypes Tle5012b::getTemperature (double & temp, int16_t & rawTemp, updTypes upd = UPD_low, safetyTypes safe = SAFE_high)
Same as above but also returns a pointer to the raw data.
Parameters
[in,out] temp pointer to 16bit double value of the temperature
[in,out] rawTemp pointer to int16_t raw value data
[in] upd read from update (UPD_high) register or directly (default, UPD_low)
[in] safe generate safety word (default, SAFE_high) or no (SAFE_low)
Returns
CRC error type
Definition at line 508 of file Tle5012b.cpp.
 {
     uint16_t rawData = 0;
     errorTypes status = readFromSensor(REG_FSYNC, rawData, upd, safe);
     if (status != NO_ERROR)
     {
         return (status);
     }
     rawData = (rawData & (DELETE_7BITS));
     //check if the value received is positive or negative
     if (rawData & CHECK_BIT_9)
     {
         rawData = rawData - CHANGE_UNIT_TO_INT_9;
     }
     rawTemp = rawData;
     temperature = (rawTemp + TEMP_OFFSET) / (TEMP_DIV);
     return (status);
 }
References CHANGE_UNIT_TO_INT_9, CHECK_BIT_9, DELETE_7BITS, NO_ERROR, readFromSensor(), REG_FSYNC, TEMP_DIV, TEMP_OFFSET, and upd.
readActivationStatus()
errorTypes Tle5012b::readActivationStatus (uint16_t & data, updTypes upd = UPD_low, safetyTypes safe = SAFE_high)
This functions reads activation status word for the sensor, which held on/off information for all optional checks and additional functions.
Parameters
[out] data pointer with the received data word
[in] upd read from update (UPD_high) register or directly (default, UPD_low)
[in] safe generate safety word (default, SAFE_high) or no (SAFE_low)
Returns
CRC error type
Definition at line 392 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_ACSTAT, data, upd, safe));
 }
References readFromSensor(), REG_ACSTAT, and upd.
readActiveStatus()
errorTypes Tle5012b::readActiveStatus (uint16_t & data)
The next functions are used primarily for storing the parameters and control of how the sensor works.
The values stored in them are used to calculate the CRC, and their values are stored in the private component of the class, _registers.
Parameters
[out] data where the data received from the _registers will be stored
Returns
CRC error typeread register offset 0x01
readBlockCRC()
errorTypes Tle5012b::readBlockCRC ()
Reads the block of _registers from addresses 08 - 0F in order to figure out the CRC.
ATTENTION: You need a memory chunk of unit16_t * CRC Registers + 1 * uint16_t for the safety word.
Returns
CRC error type
Definition at line 377 of file Tle5012b.cpp.
 {
     _command[0] = READ_BLOCK_CRC;
     uint16_t _registers[CRC_NUM_REGISTERS+1] = {0};  // Number of CRC Registers + 1 Register for Safety word
     _spiConnection->setCSPin(mCS);
     _spiConnection->sendReceiveSpi(_command, 1, _registers, CRC_NUM_REGISTERS+1);
     errorTypes checkError = checkSafety(_registers[8], READ_BLOCK_CRC, _registers, 8);
     resetSafety();
     return (checkError);
 }
References _command, _registers, _spiConnection, checkError, checkSafety(), CRC_NUM_REGISTERS, mCS, READ_BLOCK_CRC, resetSafety(), Tle5012b_SPI::sendReceiveSpi(), and Tle5012b_SPI::setCSPin().
Referenced by begin(), and regularCrcUpdate().
readFromSensor()
errorTypes Tle5012b::readFromSensor (uint16_t command, uint16_t & data, updTypes upd = UPD_low, safetyTypes safe = SAFE_high)
General read function for reading _registers from the Tle5012b.
structure of command word, the numbers represent the bit position of the 2 byte command 15 - 0 write, 1 read 14:11 - 0000 for default operational access for addresses between 0x00 - 0x04, 1010 for configuration access for addresses between 0x05 - 0x11 10 - 0 access to current value, 1 access to value in update buffer 9:4 - access to 6 bit register address 3:0 - 4 bit number of data words.
Parameters
[in] command the command for reading
[out] data where the data received from the _registers will be stored
[in] upd read from update (UPD_high) register or directly (default, UPD_low)
[in] safe generate safety word (default, SAFE_high) or not (SAFE_low)
Returns
CRC error type
Definition at line 219 of file Tle5012b.cpp.
 {
     errorTypes checkError = NO_ERROR;
     _command[0] = READ_SENSOR | command | upd | safe;
     uint16_t _received[MAX_REGISTER_MEM] = {0};
     _spiConnection->setCSPin(mCS);
     _spiConnection->sendReceiveSpi(_command, 1, _received, 2);
     data = _received[0];
     if (safe == SAFE_high)
     {
         checkError = checkSafety(_received[1], _command[0], &_received[0], 1);
         if (checkError != NO_ERROR)
         {
             data = 0;
         }
     }
     return (checkError);
 }
References _command, _received, _spiConnection, checkError, checkSafety(), command, MAX_REGISTER_MEM, mCS, NO_ERROR, READ_SENSOR, SAFE_high, Tle5012b_SPI::sendReceiveSpi(), Tle5012b_SPI::setCSPin(), and upd.
Referenced by getAngleValue(), getNumRevolutions(), getTemperature(), readActivationStatus(), readIFAB(), readIntMode1(), readIntMode2(), readIntMode3(), readIntMode4(), readOffsetX(), readOffsetY(), readRawX(), readRawY(), readSIL(), readStatus(), readSynch(), readTempCoeff(), readTempDMag(), readTempIIFCnt(), readTempRaw(), and readTempT25().
readIFAB()
errorTypes Tle5012b::readIFAB (uint16_t & data)
read register offset 0x0D
Definition at line 428 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_IFAB, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_IFAB, SAFE_high, and UPD_low.
readIntMode1()
errorTypes Tle5012b::readIntMode1 (uint16_t & data)
read register offset 0x06
Definition at line 400 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_MOD_1, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_MOD_1, SAFE_high, and UPD_low.
readIntMode2()
errorTypes Tle5012b::readIntMode2 (uint16_t & data)
read register offset 0x08
Definition at line 404 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_MOD_2, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_MOD_2, SAFE_high, and UPD_low.
Referenced by getAngleRange(), loop(), and Tle5012b_reg::setCalibration().
readIntMode3()
errorTypes Tle5012b::readIntMode3 (uint16_t & data)
read register offset 0x09
Definition at line 408 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_MOD_3, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_MOD_3, SAFE_high, and UPD_low.
Referenced by loop().
readIntMode4()
errorTypes Tle5012b::readIntMode4 (uint16_t & data)
read register offset 0x0E
Definition at line 412 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_MOD_4, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_MOD_4, SAFE_high, and UPD_low.
Referenced by Tle5012b_reg::writeInterfaceType().
readMoreRegisters()
errorTypes Tle5012b::readMoreRegisters (uint16_t command, uint16_t data[], updTypes upd = UPD_low, safetyTypes safe = SAFE_high)
Can be used to read 1 or more consecutive _registers, and the values used to read 1 or more than 1 consecutive _registers.
The maximum amount of registers are limited by the bit 3-0 of the command word, which means you can read max 15 registers and one safety word at once.
Parameters
[in] command the command for reading
[out] data where the data received from the _registers will be stored
[in] upd read from update (UPD_high) register or directly (default, UPD_low)
[in] safe generate safety word (default, SAFE_high) or no (SAFE_low)
Returns
CRC error type
Definition at line 240 of file Tle5012b.cpp.
 {
     errorTypes checkError = NO_ERROR;
     _command[0] = READ_SENSOR | command | upd | safe;
     uint16_t _received[MAX_REGISTER_MEM] = {0};
     uint16_t _recDataLength = (_command[0] & (0x000F)); // Number of registers to read
     _spiConnection->setCSPin(mCS);
     _spiConnection->sendReceiveSpi(_command, 1, _received, _recDataLength + safe);
     memcpy(data, _received, (_recDataLength)* sizeof(uint16_t));
     if (safe == SAFE_high)
     {
         checkError = checkSafety(_received[_recDataLength], _command[0], _received, _recDataLength);
         if (checkError != NO_ERROR)
         {
             data = 0;
         }
     }
     return (checkError);
 }
References _command, _received, _spiConnection, checkError, checkSafety(), command, MAX_REGISTER_MEM, mCS, NO_ERROR, READ_SENSOR, SAFE_high, Tle5012b_SPI::sendReceiveSpi(), Tle5012b_SPI::setCSPin(), and upd.
Referenced by getAngleSpeed(), loop(), and Tle5012b_reg::readSensorType().
readOffsetX()
errorTypes Tle5012b::readOffsetX (uint16_t & data)
read register offset 0x0A
Definition at line 416 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_OFFX, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_OFFX, SAFE_high, and UPD_low.
Referenced by loop().
readOffsetY()
errorTypes Tle5012b::readOffsetY (uint16_t & data)
read register offset 0x0B
Definition at line 420 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_OFFY, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_OFFY, SAFE_high, and UPD_low.
readRawX()
errorTypes Tle5012b::readRawX (int16_t & data)
The rawX value is signed 16 bit value.
Parameters
data pointer to 16bit word
Returns
CRC error type
Definition at line 452 of file Tle5012b.cpp.
 {
     uint16_t rawData = 0;
     errorTypes status = readFromSensor(REG_ADC_X, rawData);
     if (status != NO_ERROR)
     {
         return (status);
     }
     data = rawData;
     return (status);
 }
References NO_ERROR, readFromSensor(), and REG_ADC_X.
readRawY()
errorTypes Tle5012b::readRawY (int16_t & data)
The rawY value is signed 16 bit value.
Parameters
data pointer to 16bit word
Returns
CRC error type
Definition at line 463 of file Tle5012b.cpp.
 {
     uint16_t rawData = 0;
     errorTypes status = readFromSensor(REG_ADC_Y, rawData);
     if (status != NO_ERROR)
     {
         return (status);
     }
     data = rawData;
     return (status);
 }
References NO_ERROR, readFromSensor(), and REG_ADC_Y.
readSIL()
errorTypes Tle5012b::readSIL (uint16_t & data)
read register offset 0x07
Definition at line 396 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_SIL, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_SIL, SAFE_high, and UPD_low.
readStatus()
errorTypes Tle5012b::readStatus (uint16_t & data, updTypes upd = UPD_low, safetyTypes safe = SAFE_high)
This functions reads the main status word for the sensor, mainly for checking with the additional safety word.
Parameters
[out] data pointer with the received data word
[in] upd read from update (UPD_high) register or directly (default, UPD_low)
[in] safe generate safety word (default, SAFE_high) or no (SAFE_low)
Returns
CRC error type
Definition at line 388 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_STAT, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_STAT, SAFE_high, and UPD_low.
Referenced by setup(), and writeTempCoeffUpdate().
readSynch()
errorTypes Tle5012b::readSynch (uint16_t & data)
read register offset 0x0C
Definition at line 424 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_SYNCH, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_SYNCH, SAFE_high, and UPD_low.
readTempCoeff()
errorTypes Tle5012b::readTempCoeff (uint16_t & data)
read register offset 0x0F
Definition at line 432 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_TCO_Y, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_TCO_Y, SAFE_high, and UPD_low.
readTempDMag()
errorTypes Tle5012b::readTempDMag (uint16_t & data)
read register offset 0x14
Definition at line 436 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_D_MAG, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_D_MAG, SAFE_high, and UPD_low.
readTempIIFCnt()
errorTypes Tle5012b::readTempIIFCnt (uint16_t & data)
read register offset 0x20
Definition at line 440 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_IIF_CNT, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_IIF_CNT, SAFE_high, and UPD_low.
Referenced by Tle5012b_reg::readSensorType().
readTempRaw()
errorTypes Tle5012b::readTempRaw (uint16_t & data)
read register offset 0x15
Definition at line 444 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_T_RAW, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_T_RAW, SAFE_high, and UPD_low.
readTempT25()
errorTypes Tle5012b::readTempT25 (uint16_t & data)
read register offset 0x30
Definition at line 448 of file Tle5012b.cpp.
 {
     return (readFromSensor(REG_T25O, data, UPD_low, SAFE_high));
 }
References readFromSensor(), REG_T25O, SAFE_high, and UPD_low.
Referenced by Tle5012b_reg::readSensorType().
regularCrcUpdate()
errorTypes Tle5012b::regularCrcUpdate () private
This function is called each time any register in the range 08 - 0F(first byte) is changed.
It calculates the new CRC based on the value of all the _registers and then stores the value in 0F(second byte)
Returns
CRC error type
Definition at line 355 of file Tle5012b.cpp.
 {
     readBlockCRC();
     uint8_t temp[16];
     for (uint8_t i = 0; i < CRC_NUM_REGISTERS; i++)
     {
         temp[2 * i] = getFirstByte(_registers[i]);
         temp[(2 * i) + 1] = getSecondByte(_registers[i]);
     }
     uint8_t crc = crcCalc(temp, 15);
     uint16_t firstTempByte = (uint16_t) temp[14];
     uint16_t secondTempByte = (uint16_t) crc;
     uint16_t valToSend = (firstTempByte << 8) | secondTempByte;
     _registers[7] = valToSend;
     return (writeTempCoeffUpdate(valToSend));
 }
References _registers, CRC_NUM_REGISTERS, crcCalc(), getFirstByte(), getSecondByte(), readBlockCRC(), and writeTempCoeffUpdate().
Referenced by writeTempCoeffUpdate(), and writeToSensor().
resetSafety()
void Tle5012b::resetSafety () private
When an error occurs in the safety word, the error bit remains 0(error), until the status register is read again.
Flushes out safety errors, that might have occurred by reading the register without a safety word. In case the safety word sends an error, this function is called so that the error bit is reset to 1.
Definition at line 347 of file Tle5012b.cpp.
 {
     uint16_t command = READ_SENSOR + SAFE_high;
     uint16_t receive[4];
     triggerUpdate();
     _spiConnection->sendReceiveSpi(&command, 1, receive, 3);
 }
References _spiConnection, command, READ_SENSOR, SAFE_high, Tle5012b_SPI::sendReceiveSpi(), and triggerUpdate().
Referenced by checkSafety(), and readBlockCRC().
triggerUpdate()
void Tle5012b::triggerUpdate ()
Triggers an update in the register buffer.
This function should be triggered once before UPD registers where read as it generates a snapshot of the UPD register values at trigger point
Definition at line 193 of file Tle5012b.cpp.
 {
     _spiConnection->setCSPin(mCS);
     digitalWrite(mSCK, LOW);
     digitalWrite(mMOSI, HIGH);
     digitalWrite(mCS, LOW);
     //grace period for register snapshot
     delayMicroseconds(5);
     digitalWrite(mCS, HIGH);
 }
References _spiConnection, mCS, mMOSI, mSCK, and Tle5012b_SPI::setCSPin().
Referenced by loop(), Tle5012b_reg::readSensorType(), resetSafety(), setup(), and writeTempCoeffUpdate().
writeActivationStatus()
errorTypes Tle5012b::writeActivationStatus (uint16_t dataToWrite)
Standard function used for updating the CRC.
Parameters
[in] dataToWrite the new data that will be written to the register
Returns
CRC error typewrite register offset 0x01
Definition at line 646 of file Tle5012b.cpp.
 {
     return (writeToSensor(REG_ACSTAT, dataToWrite, false));
 }
References REG_ACSTAT, and writeToSensor().
Referenced by Tle5012b_reg::resetFirmware().
writeIFAB()
errorTypes Tle5012b::writeIFAB (uint16_t dataToWrite)
write register offset 0x0D
Definition at line 634 of file Tle5012b.cpp.
 {
     return (writeToSensor(REG_IFAB, dataToWrite, true));
 }
References REG_IFAB, and writeToSensor().
writeIntMode1()
errorTypes Tle5012b::writeIntMode1 (uint16_t dataToWrite)
write register offset 0x06
Definition at line 650 of file Tle5012b.cpp.
 {
     return (writeToSensor(REG_MOD_1, dataToWrite, false));
 }
References REG_MOD_1, and writeToSensor().
writeIntMode2()
errorTypes Tle5012b::writeIntMode2 (uint16_t dataToWrite)
write register offset 0x08
Definition at line 614 of file Tle5012b.cpp.
 {
     return (writeToSensor(REG_MOD_2, dataToWrite, true));
 }
References REG_MOD_2, and writeToSensor().
Referenced by loop(), and Tle5012b_reg::setCalibration().
writeIntMode3()
errorTypes Tle5012b::writeIntMode3 (uint16_t dataToWrite)
write register offset 0x09
Definition at line 618 of file Tle5012b.cpp.
 {
     return (writeToSensor(REG_MOD_3, dataToWrite, true));
 }
References REG_MOD_3, and writeToSensor().
Referenced by loop().
writeIntMode4()
errorTypes Tle5012b::writeIntMode4 (uint16_t dataToWrite)
write register offset 0x0E
Definition at line 638 of file Tle5012b.cpp.
 {
     return (writeToSensor(REG_MOD_4, dataToWrite, true));
 }
References REG_MOD_4, and writeToSensor().
Referenced by Tle5012b_reg::writeInterfaceType().
writeOffsetX()
errorTypes Tle5012b::writeOffsetX (uint16_t dataToWrite)
write register offset 0x0A
Definition at line 622 of file Tle5012b.cpp.
 {
     return (writeToSensor(REG_OFFX, dataToWrite, true));
 }
References REG_OFFX, and writeToSensor().
Referenced by loop().
writeOffsetY()
errorTypes Tle5012b::writeOffsetY (uint16_t dataToWrite)
write register offset 0x0B
Definition at line 626 of file Tle5012b.cpp.
 {
     return (writeToSensor(REG_OFFY, dataToWrite, true));
 }
References REG_OFFY, and writeToSensor().
writeSIL()
errorTypes Tle5012b::writeSIL (uint16_t dataToWrite)
write register offset 0x07
Definition at line 654 of file Tle5012b.cpp.
 {
     return (writeToSensor(REG_SIL, dataToWrite, false));
 }
References REG_SIL, and writeToSensor().
writeSlaveNumber()
errorTypes Tle5012b::writeSlaveNumber (uint16_t dataToWrite)
Function sets the SNR register with the correct slave number.
Parameters
[in] dataToWrite the new data that will be written to the register
Returns
CRC error type
Definition at line 658 of file Tle5012b.cpp.
 {
     return(writeToSensor(WRITE_SENSOR, dataToWrite, false));
 }
References WRITE_SENSOR, and writeToSensor().
Referenced by begin(), and setup().
writeSynch()
errorTypes Tle5012b::writeSynch (uint16_t dataToWrite)
write register offset 0x0C
Definition at line 630 of file Tle5012b.cpp.
 {
     return (writeToSensor(REG_SYNCH, dataToWrite, true));
 }
References REG_SYNCH, and writeToSensor().
writeTempCoeff()
errorTypes Tle5012b::writeTempCoeff (uint16_t dataToWrite)
write register offset 0x0F
Definition at line 642 of file Tle5012b.cpp.
 {
     return (writeToSensor(REG_TCO_Y, dataToWrite, true));
 }
References REG_TCO_Y, and writeToSensor().
writeTempCoeffUpdate()
errorTypes Tle5012b::writeTempCoeffUpdate (uint16_t dataToWrite)
This function is used in order to update the CRC in the register 0F(second byte)
Parameters
[in] dataToWrite the new data that will be written to the register
Returns
CRC error type
Definition at line 279 of file Tle5012b.cpp.
 {
     uint16_t safety = 0;
     uint16_t readreg = 0;
     triggerUpdate();
     _command[0] = WRITE_SENSOR | REG_TCO_Y | SAFE_high;
     _command[1] = dataToWrite;
     _spiConnection->setCSPin(mCS);
     _spiConnection->sendReceiveSpi(_command, 2, &safety, 1);
     errorTypes checkError = checkSafety(safety, _command[0], &_command[1], 1);
     //
     checkError = readStatus(readreg);
     if (readreg & 0x0008)
     {
         checkError = regularCrcUpdate();
     }
     return (checkError);
 }
References _command, _spiConnection, checkError, checkSafety(), mCS, readStatus(), REG_TCO_Y, regularCrcUpdate(), SAFE_high, Tle5012b_SPI::sendReceiveSpi(), Tle5012b_SPI::setCSPin(), triggerUpdate(), and WRITE_SENSOR.
Referenced by regularCrcUpdate().
writeToSensor()
errorTypes Tle5012b::writeToSensor (uint16_t command, uint16_t dataToWrite, bool changeCRC)
General write function for writing registers to the Tle5012b.
The safety flag will be set always and only some of all registers are writable. See documentation for further information.
Parameters
[in] command the command to execute the write
[in] dataToWrite the new data that will be written to the register
[in] changeCRC the registerIndex helps figure out in which register the value changed, so that we don't need to read all the register again to calculate the CRC
Returns
CRC error type
Definition at line 262 of file Tle5012b.cpp.
 {
     uint16_t safety = 0;
     _command[0] = WRITE_SENSOR | command | SAFE_high;
     _command[1] = dataToWrite;
     _spiConnection->setCSPin(mCS);
     _spiConnection->sendReceiveSpi(_command, 2, &safety, 1);
     errorTypes checkError = checkSafety(safety, _command[0], &_command[1], 1);
     //if we write to a register, which changes the CRC.
     if (changeCRC)
     {
     Serial.println("h45");
         checkError = regularCrcUpdate();
     }
     return (checkError);
 }
References _command, _spiConnection, checkError, checkSafety(), command, mCS, regularCrcUpdate(), SAFE_high, Tle5012b_SPI::sendReceiveSpi(), Tle5012b_SPI::setCSPin(), and WRITE_SENSOR.
Referenced by writeActivationStatus(), writeIFAB(), writeIntMode1(), writeIntMode2(), writeIntMode3(), writeIntMode4(), writeOffsetX(), writeOffsetY(), writeSIL(), writeSlaveNumber(), writeSynch(), and writeTempCoeff().
Field Documentation
_command
uint16_t Tle5012b::_command[2] private
command write data [0] = command [1] = data to write
Definition at line 465 of file Tle5012b.h.
Referenced by readBlockCRC(), readFromSensor(), readMoreRegisters(), writeTempCoeffUpdate(), and writeToSensor().
_received
uint16_t Tle5012b::_received[0x0030] private
fetched data from sensor with last word = safety word
Definition at line 466 of file Tle5012b.h.
Referenced by readFromSensor(), and readMoreRegisters().
_registers
uint16_t Tle5012b::_registers[0x0008] private
keeps track of the values stored in the 8 _registers, for which the CRC is calculated
Definition at line 467 of file Tle5012b.h.
Referenced by readBlockCRC(), and regularCrcUpdate().
_spiConnection
Tle5012b_SPI* Tle5012b::_spiConnection
SPI library for 3/4wire setup.
Definition at line 145 of file Tle5012b.h.
Referenced by begin(), readBlockCRC(), readFromSensor(), readMoreRegisters(), resetSafety(), Tle5012b(), triggerUpdate(), writeTempCoeffUpdate(), and writeToSensor().
mCS
uint8_t Tle5012b::mCS
Pin for chip select (pin 0.9 on test board)
Definition at line 165 of file Tle5012b.h.
Referenced by begin(), enableSensor(), readBlockCRC(), readFromSensor(), readMoreRegisters(), Tle5012b(), triggerUpdate(), writeTempCoeffUpdate(), and writeToSensor().
mEN
uint8_t Tle5012b::mEN
Pin to switch on/off the sensor.
Definition at line 161 of file Tle5012b.h.
Referenced by disableSensor(), enableSensor(), and Tle5012b().
mMISO
uint8_t Tle5012b::mMISO
Pin for SPI MISO (pin 0.7 on test board)
Definition at line 163 of file Tle5012b.h.
Referenced by begin(), and Tle5012b().
mMOSI
uint8_t Tle5012b::mMOSI
Pin for SPI MOSI (pin 0.6 on test board);.
Definition at line 162 of file Tle5012b.h.
Referenced by begin(), Tle5012b(), and triggerUpdate().
mSCK
uint8_t Tle5012b::mSCK
Pin for CLOCK (pin 0.8 on test board)
Definition at line 164 of file Tle5012b.h.
Referenced by begin(), Tle5012b(), and triggerUpdate().
mSlave
slaveNum Tle5012b::mSlave
actual set slave number
Definition at line 166 of file Tle5012b.h.
Referenced by begin(), and Tle5012b().
safetyStatus
safetyWord Tle5012b::safetyStatus
Definition at line 460 of file Tle5012b.h.
Referenced by setup().
safetyWord
uint16_t Tle5012b::safetyWord
the last fetched safety word
Definition at line 461 of file Tle5012b.h.
The documentation for this class was generated from the following files:
C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/src/Tle5012b.h
C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/src/Tle5012b.cpp