TLE5012B: Tle5012b_reg::stat_t Struct Reference
Tle5012b_reg::stat_t Struct Reference
< Using the inherited constructor
#include "Tle5012b_reg.h"
Public Member Functions
boolean fetch_SRST (uint16_t reg)
status reset
boolean fetch_SWD (uint16_t reg)
status watch dog
boolean fetch_SVR (uint16_t reg)
status voltage regulator
boolean fetch_SFUSE (uint16_t reg)
status fuses
boolean fetch_SDSPU (uint16_t reg)
status digital signal processing unit
boolean fetch_SXYOL (uint16_t reg)
status overflow
boolean fetch_SOV (uint16_t reg)
status X/Y data out limit
boolean fetch_SMAGOL (uint16_t reg)
status magnitude out limit
boolean fetch_Reserved1 (uint16_t reg)
reserved
boolean fetch_SADCT (uint16_t reg)
status ADC test
boolean fetch_SROM (uint16_t reg)
status ROM
boolean fetch_NOGMRXY (uint16_t reg)
no valid GMR XY Values
boolean fetch_NOGMRA (uint16_t reg)
no valid GMR Angle Value
uint8_t fetch_SNR (uint16_t reg)
slave number
boolean fetch_RDST (uint16_t reg)
read status
Data Fields
boolean RDST
bits 15:15 Read status
uint8_t SNR
bits 14:13 Slave number
boolean NOGMRA
bits 12:12 No valid GMR angle value
boolean NOGMRXY
bits 11:11 No valid GMR XY values
boolean SROM
bits 10:10 Status ROM
boolean SADCT
bits 9:9 Status ADC Test
boolean Reserved1
bits 8:8
boolean SMAGOL
bits 7:7 Status magnitude out of Limit
boolean SXYOL
bits 6:6 Status X,Y Data out of Limit
boolean SOV
bits 5:5 Status overflow
boolean SDSPU
bits 4:4 Status digital signal processing unit
boolean SFUSE
bits 3:3 Status fuse CRC
boolean SVR
bits 2:2 Status voltage regulator
boolean SWD
bits 1:1 Status Watch dog
boolean SRST
bits 0:0 Status Reset
uint16_t reg
the register value
Detailed Description
< Using the inherited constructor
< Status register 0x00
Definition at line 86 of file Tle5012b_reg.h.
Member Function Documentation
fetch_NOGMRA()
boolean Tle5012b_reg::stat_t::fetch_NOGMRA (uint16_t reg) inline
no valid GMR Angle Value
Definition at line 117 of file Tle5012b_reg.h.
References NOGMRA, and reg.
Referenced by reg_stat().
fetch_NOGMRXY()
boolean Tle5012b_reg::stat_t::fetch_NOGMRXY (uint16_t reg) inline
no valid GMR XY Values
Definition at line 116 of file Tle5012b_reg.h.
References NOGMRXY, and reg.
Referenced by reg_stat().
fetch_RDST()
boolean Tle5012b_reg::stat_t::fetch_RDST (uint16_t reg) inline
read status
Definition at line 119 of file Tle5012b_reg.h.
References RDST, and reg.
Referenced by reg_stat().
fetch_Reserved1()
boolean Tle5012b_reg::stat_t::fetch_Reserved1 (uint16_t reg) inline
reserved
Definition at line 113 of file Tle5012b_reg.h.
References reg, and Reserved1.
Referenced by reg_stat().
fetch_SADCT()
boolean Tle5012b_reg::stat_t::fetch_SADCT (uint16_t reg) inline
status ADC test
Definition at line 114 of file Tle5012b_reg.h.
References reg, and SADCT.
Referenced by reg_stat().
fetch_SDSPU()
boolean Tle5012b_reg::stat_t::fetch_SDSPU (uint16_t reg) inline
status digital signal processing unit
Definition at line 109 of file Tle5012b_reg.h.
References reg, and SDSPU.
Referenced by reg_stat().
fetch_SFUSE()
boolean Tle5012b_reg::stat_t::fetch_SFUSE (uint16_t reg) inline
status fuses
Definition at line 108 of file Tle5012b_reg.h.
References reg, and SFUSE.
Referenced by reg_stat().
fetch_SMAGOL()
boolean Tle5012b_reg::stat_t::fetch_SMAGOL (uint16_t reg) inline
status magnitude out limit
Definition at line 112 of file Tle5012b_reg.h.
References reg, and SMAGOL.
Referenced by reg_stat().
fetch_SNR()
uint8_t Tle5012b_reg::stat_t::fetch_SNR (uint16_t reg) inline
slave number
Definition at line 118 of file Tle5012b_reg.h.
References reg, and SNR.
Referenced by Tle5012b_reg::identifyInterfaceType(), reg_stat(), and setup().
fetch_SOV()
boolean Tle5012b_reg::stat_t::fetch_SOV (uint16_t reg) inline
status X/Y data out limit
Definition at line 111 of file Tle5012b_reg.h.
References reg, and SOV.
Referenced by reg_stat().
fetch_SROM()
boolean Tle5012b_reg::stat_t::fetch_SROM (uint16_t reg) inline
status ROM
Definition at line 115 of file Tle5012b_reg.h.
References reg, and SROM.
Referenced by reg_stat().
fetch_SRST()
boolean Tle5012b_reg::stat_t::fetch_SRST (uint16_t reg) inline
status reset
Definition at line 105 of file Tle5012b_reg.h.
References reg, and SRST.
Referenced by reg_stat().
fetch_SVR()
boolean Tle5012b_reg::stat_t::fetch_SVR (uint16_t reg) inline
status voltage regulator
Definition at line 107 of file Tle5012b_reg.h.
References reg, and SVR.
Referenced by reg_stat().
fetch_SWD()
boolean Tle5012b_reg::stat_t::fetch_SWD (uint16_t reg) inline
status watch dog
Definition at line 106 of file Tle5012b_reg.h.
References reg, and SWD.
Referenced by reg_stat().
fetch_SXYOL()
boolean Tle5012b_reg::stat_t::fetch_SXYOL (uint16_t reg) inline
status overflow
Definition at line 110 of file Tle5012b_reg.h.
References reg, and SXYOL.
Referenced by reg_stat().
Field Documentation
NOGMRA
boolean Tle5012b_reg::stat_t::NOGMRA
bits 12:12 No valid GMR angle value
Definition at line 90 of file Tle5012b_reg.h.
Referenced by fetch_NOGMRA().
NOGMRXY
boolean Tle5012b_reg::stat_t::NOGMRXY
bits 11:11 No valid GMR XY values
Definition at line 91 of file Tle5012b_reg.h.
Referenced by fetch_NOGMRXY().
RDST
boolean Tle5012b_reg::stat_t::RDST
bits 15:15 Read status
Definition at line 88 of file Tle5012b_reg.h.
Referenced by fetch_RDST().
reg
uint16_t Tle5012b_reg::stat_t::reg
the register value
Definition at line 103 of file Tle5012b_reg.h.
Referenced by fetch_NOGMRA(), fetch_NOGMRXY(), fetch_RDST(), fetch_Reserved1(), fetch_SADCT(), fetch_SDSPU(), fetch_SFUSE(), fetch_SMAGOL(), fetch_SNR(), fetch_SOV(), fetch_SROM(), fetch_SRST(), fetch_SVR(), fetch_SWD(), fetch_SXYOL(), Tle5012b_reg::identifyInterfaceType(), Tle5012b_reg::readSensorType(), and reg_stat().
Reserved1
boolean Tle5012b_reg::stat_t::Reserved1
bits 8:8
Definition at line 94 of file Tle5012b_reg.h.
Referenced by fetch_Reserved1().
SADCT
boolean Tle5012b_reg::stat_t::SADCT
bits 9:9 Status ADC Test
Definition at line 93 of file Tle5012b_reg.h.
Referenced by fetch_SADCT().
SDSPU
boolean Tle5012b_reg::stat_t::SDSPU
bits 4:4 Status digital signal processing unit
Definition at line 98 of file Tle5012b_reg.h.
Referenced by fetch_SDSPU().
SFUSE
boolean Tle5012b_reg::stat_t::SFUSE
bits 3:3 Status fuse CRC
Definition at line 99 of file Tle5012b_reg.h.
Referenced by fetch_SFUSE().
SMAGOL
boolean Tle5012b_reg::stat_t::SMAGOL
bits 7:7 Status magnitude out of Limit
Definition at line 95 of file Tle5012b_reg.h.
Referenced by fetch_SMAGOL().
SNR
uint8_t Tle5012b_reg::stat_t::SNR
bits 14:13 Slave number
Definition at line 89 of file Tle5012b_reg.h.
Referenced by fetch_SNR(), and setup().
SOV
boolean Tle5012b_reg::stat_t::SOV
bits 5:5 Status overflow
Definition at line 97 of file Tle5012b_reg.h.
Referenced by fetch_SOV().
SROM
boolean Tle5012b_reg::stat_t::SROM
bits 10:10 Status ROM
Definition at line 92 of file Tle5012b_reg.h.
Referenced by fetch_SROM().
SRST
boolean Tle5012b_reg::stat_t::SRST
bits 0:0 Status Reset
Definition at line 102 of file Tle5012b_reg.h.
Referenced by fetch_SRST().
SVR
boolean Tle5012b_reg::stat_t::SVR
bits 2:2 Status voltage regulator
Definition at line 100 of file Tle5012b_reg.h.
Referenced by fetch_SVR().
SWD
boolean Tle5012b_reg::stat_t::SWD
bits 1:1 Status Watch dog
Definition at line 101 of file Tle5012b_reg.h.
Referenced by fetch_SWD().
SXYOL
boolean Tle5012b_reg::stat_t::SXYOL
bits 6:6 Status X,Y Data out of Limit
Definition at line 96 of file Tle5012b_reg.h.
Referenced by fetch_SXYOL().
The documentation for this struct was generated from the following file:
C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/src/Tle5012b_reg.h