TLE5012B: C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/examples/Read_Write_Registers/Read_Write_Registers.ino File Reference
Read_Write_Registers.ino File Reference
#include "Tle5012b.h"
Read_Write_Registrs
This example show how to use the register write functions of the sensor, to change certain bits with deafult low speed 9600 baud comunication and standard sensor settings
Author
Infineon Technologies AG
Copyright
2019 Infineon Technologies AG
Version
2.0.1
Tle5012b Tle5012MagneticAngleSensor
errorTypes checkError = NO_ERROR
bool s = true
void setup ()
void loop ()
Function Documentation
loop()
void loop ()
Definition at line 29 of file Read_Write_Registers.ino.
             {
   if (s && (checkError == 0))
   {
     uint16_t a = 0;
     checkError = Tle5012MagneticAngleSensor.readIntMode2(a);
     Serial.print("read intmode2:\t0x");
     Serial.print(a,HEX);
     Serial.print("\tcheckError: ");
     Serial.println(checkError,HEX);
     checkError  = Tle5012MagneticAngleSensor.writeIntMode2(0x804);
     Serial.print("write intmode2:\t0x804\tcheckError: ");
     Serial.println(checkError,HEX);
     checkError = Tle5012MagneticAngleSensor.readIntMode2(a);
     Serial.print("read intmode2:\t0x");
     Serial.print(a,HEX);
     Serial.print("\tcheckError: ");
     Serial.println(checkError,HEX);
     Serial.println("");
     //
     checkError = Tle5012MagneticAngleSensor.readIntMode3(a);
     Serial.print("read intmode3:\t0x");
     Serial.print(a,HEX);
     Serial.print("\tcheckError: ");
     Serial.println(checkError,HEX);
     checkError  = Tle5012MagneticAngleSensor.writeIntMode3(0x8000);
     Serial.print("write intmode3:\t0x8000\tcheckError: ");
     Serial.println(checkError,HEX);
     checkError = Tle5012MagneticAngleSensor.readIntMode3(a);
     Serial.print("read intmode3:\t0x");
     Serial.print(a,HEX);
     Serial.print("\tcheckError: ");
     Serial.println(checkError,HEX);
     Serial.println("");
     //
     checkError = Tle5012MagneticAngleSensor.readOffsetX(a);
     Serial.print("read OffsetX:\t0x");
     Serial.print(a,HEX);
     Serial.print("\tcheckError: ");
     Serial.println(checkError,HEX);
     checkError  = Tle5012MagneticAngleSensor.writeOffsetX(0xD960);
     Serial.print("write OffsetX;\t0xD960\tcheckError: ");
     Serial.println(checkError,HEX);
     checkError = Tle5012MagneticAngleSensor.readOffsetX(a);
     Serial.print("read OffsetX:\t0x");
     Serial.print(a,HEX);
     Serial.print("\tcheckError: ");
     Serial.println(checkError,HEX);
     s = false;
   }
 }
References checkError, Tle5012b::readIntMode2(), Tle5012b::readIntMode3(), Tle5012b::readOffsetX(), s, Tle5012MagneticAngleSensor, Tle5012b::writeIntMode2(), Tle5012b::writeIntMode3(), and Tle5012b::writeOffsetX().
setup()
void setup ()
Definition at line 19 of file Read_Write_Registers.ino.
              {
   delay(2000);
   Serial.begin(9600);
   Serial.println("init done!\n");
   checkError = Tle5012MagneticAngleSensor.begin();
   Serial.print("checkerror: ");
   Serial.println(checkError, HEX);
   delay(1000);
 }
References Tle5012b::begin(), checkError, and Tle5012MagneticAngleSensor.
Variable Documentation
checkError
errorTypes checkError = NO_ERROR
Definition at line 16 of file Read_Write_Registers.ino.
Referenced by loop(), and setup().
s
bool s = true
Definition at line 17 of file Read_Write_Registers.ino.
Referenced by loop().
Tle5012MagneticAngleSensor
Tle5012b Tle5012MagneticAngleSensor
Definition at line 15 of file Read_Write_Registers.ino.
Referenced by loop(), and setup().