TLE5012B: Tle5012b_reg::ifab_t Struct Reference
Tle5012b_reg::ifab_t Struct Reference
#include "Tle5012b_reg.h"
Public Member Functions
uint8_t fetch_IFADHYST (uint16_t reg)
boolean fetch_IFABOD (uint16_t reg)
boolean fetch_FIRUDR (uint16_t reg)
int16_t fetch_ORTHO (uint16_t reg)
Data Fields
int16_t ORTHO
< IFAB register offset 0x0d
boolean FIRUDR
bits 3:3 Initial filter update rate (FIR)
boolean IFABOD
bits 2:2 IFA,IFB,IFC Output Mode
uint8_t IFADHYST
bits 1:0 Hysteresis (multi-purpose)
uint16_t reg
the register value
Detailed Description
Definition at line 335 of file Tle5012b_reg.h.
Member Function Documentation
fetch_FIRUDR()
boolean Tle5012b_reg::ifab_t::fetch_FIRUDR (uint16_t reg) inline
Definition at line 344 of file Tle5012b_reg.h.
 {FIRUDR = (reg & 0x8) >> 3;return (FIRUDR);}
References FIRUDR, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), reg_ifab(), and setup().
fetch_IFABOD()
boolean Tle5012b_reg::ifab_t::fetch_IFABOD (uint16_t reg) inline
Definition at line 343 of file Tle5012b_reg.h.
 {IFABOD = (reg & 0x4) >> 2;return (IFABOD);}
References IFABOD, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), reg_ifab(), and setup().
fetch_IFADHYST()
uint8_t Tle5012b_reg::ifab_t::fetch_IFADHYST (uint16_t reg) inline
Definition at line 342 of file Tle5012b_reg.h.
 {IFADHYST = (reg & 0x3);return (IFADHYST);}
References IFADHYST, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), reg_ifab(), and setup().
fetch_ORTHO()
int16_t Tle5012b_reg::ifab_t::fetch_ORTHO (uint16_t reg) inline
Definition at line 345 of file Tle5012b_reg.h.
{
             ORTHO = ((reg & 0xFFF0) >> 4);
             if (ORTHO & 0x800) {
                 ORTHO = ORTHO * -1;
             }
             return (ORTHO);
         }
References ORTHO, and reg.
Referenced by reg_ifab().
Field Documentation
FIRUDR
boolean Tle5012b_reg::ifab_t::FIRUDR
bits 3:3 Initial filter update rate (FIR)
Definition at line 337 of file Tle5012b_reg.h.
Referenced by fetch_FIRUDR(), and Tle5012b_reg::identify().
IFABOD
boolean Tle5012b_reg::ifab_t::IFABOD
bits 2:2 IFA,IFB,IFC Output Mode
Definition at line 338 of file Tle5012b_reg.h.
Referenced by fetch_IFABOD(), and Tle5012b_reg::identify().
IFADHYST
uint8_t Tle5012b_reg::ifab_t::IFADHYST
bits 1:0 Hysteresis (multi-purpose)
Definition at line 339 of file Tle5012b_reg.h.
Referenced by fetch_IFADHYST().
ORTHO
int16_t Tle5012b_reg::ifab_t::ORTHO
< IFAB register offset 0x0d
bits 15:4 Orthogonality Correction of X and Y Components
Definition at line 336 of file Tle5012b_reg.h.
Referenced by fetch_ORTHO().
reg
uint16_t Tle5012b_reg::ifab_t::reg
the register value
Definition at line 340 of file Tle5012b_reg.h.
Referenced by fetch_FIRUDR(), fetch_IFABOD(), fetch_IFADHYST(), fetch_ORTHO(), Tle5012b_reg::identifyInterfaceType(), Tle5012b_reg::readSensorType(), reg_ifab(), and setup().
The documentation for this struct was generated from the following file:
C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/src/Tle5012b_reg.h