TLE5012B: Tle5012b_reg::mod4_t Struct Reference
Tle5012b_reg::mod4_t Struct Reference
#include "Tle5012b_reg.h"
Public Member Functions
uint8_t fetch_IFMD (uint16_t reg)
boolean fetch_Reserverd1 (uint16_t reg)
uint8_t fetch_IFABRES (uint16_t reg)
uint8_t fetch_HSMPLP (uint16_t reg)
int8_t fetch_TCOXT (uint16_t reg)
Data Fields
int8_t TCOXT
< MOD_4 Interface Mode4 register offset 0x0e
uint8_t HSMPLP
bits 8:5 Hall Switch mode (multi-purpose)
uint8_t IFABRES
bits 4:3 IIF resolution (multi-purpose)
boolean Reserverd1
bits 2:2
uint8_t IFMD
bits 1:0 Interface Mode on IFA,IFB,IFC
uint16_t reg
the register value
Detailed Description
Definition at line 354 of file Tle5012b_reg.h.
Member Function Documentation
fetch_HSMPLP()
uint8_t Tle5012b_reg::mod4_t::fetch_HSMPLP (uint16_t reg) inline
Definition at line 365 of file Tle5012b_reg.h.
 {HSMPLP = (reg & 0x1E0) >> 5;return (HSMPLP);}
References HSMPLP, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), and reg_mod4().
fetch_IFABRES()
uint8_t Tle5012b_reg::mod4_t::fetch_IFABRES (uint16_t reg) inline
Definition at line 364 of file Tle5012b_reg.h.
 {IFABRES = (reg & 0x18) >> 3;return (IFABRES);}
References IFABRES, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), reg_mod4(), and setup().
fetch_IFMD()
uint8_t Tle5012b_reg::mod4_t::fetch_IFMD (uint16_t reg) inline
Definition at line 362 of file Tle5012b_reg.h.
 {IFMD = (reg & 0x3);return (IFMD);}
References IFMD, and reg.
Referenced by Tle5012b_reg::identifyInterfaceType(), and reg_mod4().
fetch_Reserverd1()
boolean Tle5012b_reg::mod4_t::fetch_Reserverd1 (uint16_t reg) inline
Definition at line 363 of file Tle5012b_reg.h.
 {Reserverd1 = (reg & 0x4) >> 2;return (Reserverd1);}
References reg, and Reserverd1.
fetch_TCOXT()
int8_t Tle5012b_reg::mod4_t::fetch_TCOXT (uint16_t reg) inline
Definition at line 366 of file Tle5012b_reg.h.
{
             TCOXT = ((reg & 0x7E00) >> 9);
             if (TCOXT & 0x8000) {
                 TCOXT = TCOXT * -1;
             }
             return (TCOXT);
         }
References reg, and TCOXT.
Referenced by reg_mod4().
Field Documentation
HSMPLP
uint8_t Tle5012b_reg::mod4_t::HSMPLP
bits 8:5 Hall Switch mode (multi-purpose)
Definition at line 356 of file Tle5012b_reg.h.
Referenced by fetch_HSMPLP().
IFABRES
uint8_t Tle5012b_reg::mod4_t::IFABRES
bits 4:3 IIF resolution (multi-purpose)
Definition at line 357 of file Tle5012b_reg.h.
Referenced by fetch_IFABRES().
IFMD
uint8_t Tle5012b_reg::mod4_t::IFMD
bits 1:0 Interface Mode on IFA,IFB,IFC
Definition at line 359 of file Tle5012b_reg.h.
Referenced by fetch_IFMD(), and Tle5012b_reg::identify().
reg
uint16_t Tle5012b_reg::mod4_t::reg
the register value
Definition at line 360 of file Tle5012b_reg.h.
Referenced by fetch_HSMPLP(), fetch_IFABRES(), fetch_IFMD(), fetch_Reserverd1(), fetch_TCOXT(), Tle5012b_reg::identifyInterfaceType(), Tle5012b_reg::readSensorType(), reg_mod4(), and setup().
Reserverd1
boolean Tle5012b_reg::mod4_t::Reserverd1
bits 2:2
Definition at line 358 of file Tle5012b_reg.h.
Referenced by fetch_Reserverd1().
TCOXT
int8_t Tle5012b_reg::mod4_t::TCOXT
< MOD_4 Interface Mode4 register offset 0x0e
bits 15:9 7-bit signed integer value of X-offset temperature coefficient.
Definition at line 355 of file Tle5012b_reg.h.
Referenced by fetch_TCOXT().
The documentation for this struct was generated from the following file:
C:/Users/Enriquez/Documents/Arduino/libraries/tle5012b/src/Tle5012b_reg.h